# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import buyer_pb2 as buyer__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in buyer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BuyerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBuyer = channel.unary_unary(
                '/buyer.BuyerService/CreateBuyer',
                request_serializer=buyer__pb2.CreateBuyerRequest.SerializeToString,
                response_deserializer=buyer__pb2.CreateBuyerResponse.FromString,
                _registered_method=True)
        self.LoginBuyer = channel.unary_unary(
                '/buyer.BuyerService/LoginBuyer',
                request_serializer=buyer__pb2.LoginBuyerRequest.SerializeToString,
                response_deserializer=buyer__pb2.LoginBuyerResponse.FromString,
                _registered_method=True)
        self.LogoutBuyer = channel.unary_unary(
                '/buyer.BuyerService/LogoutBuyer',
                request_serializer=buyer__pb2.LogoutBuyerRequest.SerializeToString,
                response_deserializer=buyer__pb2.LogoutBuyerResponse.FromString,
                _registered_method=True)
        self.ValidateSession = channel.unary_unary(
                '/buyer.BuyerService/ValidateSession',
                request_serializer=buyer__pb2.ValidateSessionRequest.SerializeToString,
                response_deserializer=buyer__pb2.ValidateSessionResponse.FromString,
                _registered_method=True)
        self.TouchSession = channel.unary_unary(
                '/buyer.BuyerService/TouchSession',
                request_serializer=buyer__pb2.TouchSessionRequest.SerializeToString,
                response_deserializer=buyer__pb2.TouchSessionResponse.FromString,
                _registered_method=True)
        self.SearchItems = channel.unary_unary(
                '/buyer.BuyerService/SearchItems',
                request_serializer=buyer__pb2.SearchItemsRequest.SerializeToString,
                response_deserializer=buyer__pb2.SearchItemsResponse.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/buyer.BuyerService/GetItem',
                request_serializer=buyer__pb2.GetItemRequest.SerializeToString,
                response_deserializer=buyer__pb2.GetItemResponse.FromString,
                _registered_method=True)
        self.AddToCart = channel.unary_unary(
                '/buyer.BuyerService/AddToCart',
                request_serializer=buyer__pb2.AddToCartRequest.SerializeToString,
                response_deserializer=buyer__pb2.AddToCartResponse.FromString,
                _registered_method=True)
        self.RemoveFromCart = channel.unary_unary(
                '/buyer.BuyerService/RemoveFromCart',
                request_serializer=buyer__pb2.RemoveFromCartRequest.SerializeToString,
                response_deserializer=buyer__pb2.RemoveFromCartResponse.FromString,
                _registered_method=True)
        self.GetCart = channel.unary_unary(
                '/buyer.BuyerService/GetCart',
                request_serializer=buyer__pb2.GetCartRequest.SerializeToString,
                response_deserializer=buyer__pb2.GetCartResponse.FromString,
                _registered_method=True)
        self.ClearCart = channel.unary_unary(
                '/buyer.BuyerService/ClearCart',
                request_serializer=buyer__pb2.ClearCartRequest.SerializeToString,
                response_deserializer=buyer__pb2.ClearCartResponse.FromString,
                _registered_method=True)
        self.SaveCart = channel.unary_unary(
                '/buyer.BuyerService/SaveCart',
                request_serializer=buyer__pb2.SaveCartRequest.SerializeToString,
                response_deserializer=buyer__pb2.SaveCartResponse.FromString,
                _registered_method=True)
        self.ProvideItemFeedback = channel.unary_unary(
                '/buyer.BuyerService/ProvideItemFeedback',
                request_serializer=buyer__pb2.ProvideItemFeedbackRequest.SerializeToString,
                response_deserializer=buyer__pb2.ProvideItemFeedbackResponse.FromString,
                _registered_method=True)
        self.GetSellerRating = channel.unary_unary(
                '/buyer.BuyerService/GetSellerRating',
                request_serializer=buyer__pb2.GetSellerRatingRequest.SerializeToString,
                response_deserializer=buyer__pb2.GetSellerRatingResponse.FromString,
                _registered_method=True)
        self.GetBuyerPurchases = channel.unary_unary(
                '/buyer.BuyerService/GetBuyerPurchases',
                request_serializer=buyer__pb2.GetBuyerPurchasesRequest.SerializeToString,
                response_deserializer=buyer__pb2.GetBuyerPurchasesResponse.FromString,
                _registered_method=True)
        self.MakePurchase = channel.unary_unary(
                '/buyer.BuyerService/MakePurchase',
                request_serializer=buyer__pb2.MakePurchaseRequest.SerializeToString,
                response_deserializer=buyer__pb2.MakePurchaseResponse.FromString,
                _registered_method=True)


class BuyerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateBuyer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginBuyer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogoutBuyer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TouchSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFromCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProvideItemFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerRating(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuyerPurchases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakePurchase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BuyerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBuyer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBuyer,
                    request_deserializer=buyer__pb2.CreateBuyerRequest.FromString,
                    response_serializer=buyer__pb2.CreateBuyerResponse.SerializeToString,
            ),
            'LoginBuyer': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginBuyer,
                    request_deserializer=buyer__pb2.LoginBuyerRequest.FromString,
                    response_serializer=buyer__pb2.LoginBuyerResponse.SerializeToString,
            ),
            'LogoutBuyer': grpc.unary_unary_rpc_method_handler(
                    servicer.LogoutBuyer,
                    request_deserializer=buyer__pb2.LogoutBuyerRequest.FromString,
                    response_serializer=buyer__pb2.LogoutBuyerResponse.SerializeToString,
            ),
            'ValidateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateSession,
                    request_deserializer=buyer__pb2.ValidateSessionRequest.FromString,
                    response_serializer=buyer__pb2.ValidateSessionResponse.SerializeToString,
            ),
            'TouchSession': grpc.unary_unary_rpc_method_handler(
                    servicer.TouchSession,
                    request_deserializer=buyer__pb2.TouchSessionRequest.FromString,
                    response_serializer=buyer__pb2.TouchSessionResponse.SerializeToString,
            ),
            'SearchItems': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItems,
                    request_deserializer=buyer__pb2.SearchItemsRequest.FromString,
                    response_serializer=buyer__pb2.SearchItemsResponse.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=buyer__pb2.GetItemRequest.FromString,
                    response_serializer=buyer__pb2.GetItemResponse.SerializeToString,
            ),
            'AddToCart': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToCart,
                    request_deserializer=buyer__pb2.AddToCartRequest.FromString,
                    response_serializer=buyer__pb2.AddToCartResponse.SerializeToString,
            ),
            'RemoveFromCart': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFromCart,
                    request_deserializer=buyer__pb2.RemoveFromCartRequest.FromString,
                    response_serializer=buyer__pb2.RemoveFromCartResponse.SerializeToString,
            ),
            'GetCart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCart,
                    request_deserializer=buyer__pb2.GetCartRequest.FromString,
                    response_serializer=buyer__pb2.GetCartResponse.SerializeToString,
            ),
            'ClearCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCart,
                    request_deserializer=buyer__pb2.ClearCartRequest.FromString,
                    response_serializer=buyer__pb2.ClearCartResponse.SerializeToString,
            ),
            'SaveCart': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCart,
                    request_deserializer=buyer__pb2.SaveCartRequest.FromString,
                    response_serializer=buyer__pb2.SaveCartResponse.SerializeToString,
            ),
            'ProvideItemFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.ProvideItemFeedback,
                    request_deserializer=buyer__pb2.ProvideItemFeedbackRequest.FromString,
                    response_serializer=buyer__pb2.ProvideItemFeedbackResponse.SerializeToString,
            ),
            'GetSellerRating': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerRating,
                    request_deserializer=buyer__pb2.GetSellerRatingRequest.FromString,
                    response_serializer=buyer__pb2.GetSellerRatingResponse.SerializeToString,
            ),
            'GetBuyerPurchases': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuyerPurchases,
                    request_deserializer=buyer__pb2.GetBuyerPurchasesRequest.FromString,
                    response_serializer=buyer__pb2.GetBuyerPurchasesResponse.SerializeToString,
            ),
            'MakePurchase': grpc.unary_unary_rpc_method_handler(
                    servicer.MakePurchase,
                    request_deserializer=buyer__pb2.MakePurchaseRequest.FromString,
                    response_serializer=buyer__pb2.MakePurchaseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'buyer.BuyerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('buyer.BuyerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BuyerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateBuyer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buyer.BuyerService/CreateBuyer',
            buyer__pb2.CreateBuyerRequest.SerializeToString,
            buyer__pb2.CreateBuyerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoginBuyer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buyer.BuyerService/LoginBuyer',
            buyer__pb2.LoginBuyerRequest.SerializeToString,
            buyer__pb2.LoginBuyerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LogoutBuyer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buyer.BuyerService/LogoutBuyer',
            buyer__pb2.LogoutBuyerRequest.SerializeToString,
            buyer__pb2.LogoutBuyerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buyer.BuyerService/ValidateSession',
            buyer__pb2.ValidateSessionRequest.SerializeToString,
            buyer__pb2.ValidateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TouchSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buyer.BuyerService/TouchSession',
            buyer__pb2.TouchSessionRequest.SerializeToString,
            buyer__pb2.TouchSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buyer.BuyerService/SearchItems',
            buyer__pb2.SearchItemsRequest.SerializeToString,
            buyer__pb2.SearchItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buyer.BuyerService/GetItem',
            buyer__pb2.GetItemRequest.SerializeToString,
            buyer__pb2.GetItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddToCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buyer.BuyerService/AddToCart',
            buyer__pb2.AddToCartRequest.SerializeToString,
            buyer__pb2.AddToCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveFromCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buyer.BuyerService/RemoveFromCart',
            buyer__pb2.RemoveFromCartRequest.SerializeToString,
            buyer__pb2.RemoveFromCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buyer.BuyerService/GetCart',
            buyer__pb2.GetCartRequest.SerializeToString,
            buyer__pb2.GetCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buyer.BuyerService/ClearCart',
            buyer__pb2.ClearCartRequest.SerializeToString,
            buyer__pb2.ClearCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buyer.BuyerService/SaveCart',
            buyer__pb2.SaveCartRequest.SerializeToString,
            buyer__pb2.SaveCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProvideItemFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buyer.BuyerService/ProvideItemFeedback',
            buyer__pb2.ProvideItemFeedbackRequest.SerializeToString,
            buyer__pb2.ProvideItemFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSellerRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buyer.BuyerService/GetSellerRating',
            buyer__pb2.GetSellerRatingRequest.SerializeToString,
            buyer__pb2.GetSellerRatingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBuyerPurchases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buyer.BuyerService/GetBuyerPurchases',
            buyer__pb2.GetBuyerPurchasesRequest.SerializeToString,
            buyer__pb2.GetBuyerPurchasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakePurchase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buyer.BuyerService/MakePurchase',
            buyer__pb2.MakePurchaseRequest.SerializeToString,
            buyer__pb2.MakePurchaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
