# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import product_pb2 as product__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in product_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductServiceStub(object):
    """---------------------------------------------------------------------------
    Service definition
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchItems = channel.unary_unary(
                '/product.ProductService/SearchItems',
                request_serializer=product__pb2.SearchItemsRequest.SerializeToString,
                response_deserializer=product__pb2.SearchItemsResponse.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/product.ProductService/GetItem',
                request_serializer=product__pb2.GetItemRequest.SerializeToString,
                response_deserializer=product__pb2.GetItemResponse.FromString,
                _registered_method=True)
        self.GetCart = channel.unary_unary(
                '/product.ProductService/GetCart',
                request_serializer=product__pb2.GetCartRequest.SerializeToString,
                response_deserializer=product__pb2.GetCartResponse.FromString,
                _registered_method=True)
        self.GetBuyerPurchases = channel.unary_unary(
                '/product.ProductService/GetBuyerPurchases',
                request_serializer=product__pb2.GetBuyerPurchasesRequest.SerializeToString,
                response_deserializer=product__pb2.GetBuyerPurchasesResponse.FromString,
                _registered_method=True)
        self.DisplayItems = channel.unary_unary(
                '/product.ProductService/DisplayItems',
                request_serializer=product__pb2.DisplayItemsRequest.SerializeToString,
                response_deserializer=product__pb2.DisplayItemsResponse.FromString,
                _registered_method=True)
        self.AddToCart = channel.unary_unary(
                '/product.ProductService/AddToCart',
                request_serializer=product__pb2.AddToCartRequest.SerializeToString,
                response_deserializer=product__pb2.AddToCartResponse.FromString,
                _registered_method=True)
        self.RemoveFromCart = channel.unary_unary(
                '/product.ProductService/RemoveFromCart',
                request_serializer=product__pb2.RemoveFromCartRequest.SerializeToString,
                response_deserializer=product__pb2.RemoveFromCartResponse.FromString,
                _registered_method=True)
        self.ClearCart = channel.unary_unary(
                '/product.ProductService/ClearCart',
                request_serializer=product__pb2.ClearCartRequest.SerializeToString,
                response_deserializer=product__pb2.ClearCartResponse.FromString,
                _registered_method=True)
        self.ClearUnsavedCart = channel.unary_unary(
                '/product.ProductService/ClearUnsavedCart',
                request_serializer=product__pb2.ClearUnsavedCartRequest.SerializeToString,
                response_deserializer=product__pb2.ClearUnsavedCartResponse.FromString,
                _registered_method=True)
        self.SaveCart = channel.unary_unary(
                '/product.ProductService/SaveCart',
                request_serializer=product__pb2.SaveCartRequest.SerializeToString,
                response_deserializer=product__pb2.SaveCartResponse.FromString,
                _registered_method=True)
        self.ProvideItemFeedback = channel.unary_unary(
                '/product.ProductService/ProvideItemFeedback',
                request_serializer=product__pb2.ProvideItemFeedbackRequest.SerializeToString,
                response_deserializer=product__pb2.ProvideItemFeedbackResponse.FromString,
                _registered_method=True)
        self.MakePurchase = channel.unary_unary(
                '/product.ProductService/MakePurchase',
                request_serializer=product__pb2.MakePurchaseRequest.SerializeToString,
                response_deserializer=product__pb2.MakePurchaseResponse.FromString,
                _registered_method=True)
        self.RegisterItem = channel.unary_unary(
                '/product.ProductService/RegisterItem',
                request_serializer=product__pb2.RegisterItemRequest.SerializeToString,
                response_deserializer=product__pb2.RegisterItemResponse.FromString,
                _registered_method=True)
        self.UpdateUnitsForSale = channel.unary_unary(
                '/product.ProductService/UpdateUnitsForSale',
                request_serializer=product__pb2.UpdateUnitsForSaleRequest.SerializeToString,
                response_deserializer=product__pb2.UpdateUnitsForSaleResponse.FromString,
                _registered_method=True)
        self.ChangeItemPrice = channel.unary_unary(
                '/product.ProductService/ChangeItemPrice',
                request_serializer=product__pb2.ChangeItemPriceRequest.SerializeToString,
                response_deserializer=product__pb2.ChangeItemPriceResponse.FromString,
                _registered_method=True)


class ProductServiceServicer(object):
    """---------------------------------------------------------------------------
    Service definition
    ---------------------------------------------------------------------------

    """

    def SearchItems(self, request, context):
        """Reads — served from local MySQL, no Raft
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuyerPurchases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisplayItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToCart(self, request, context):
        """Writes — replicated via Raft before being applied to local MySQL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFromCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearUnsavedCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProvideItemFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakePurchase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUnitsForSale(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeItemPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchItems': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItems,
                    request_deserializer=product__pb2.SearchItemsRequest.FromString,
                    response_serializer=product__pb2.SearchItemsResponse.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=product__pb2.GetItemRequest.FromString,
                    response_serializer=product__pb2.GetItemResponse.SerializeToString,
            ),
            'GetCart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCart,
                    request_deserializer=product__pb2.GetCartRequest.FromString,
                    response_serializer=product__pb2.GetCartResponse.SerializeToString,
            ),
            'GetBuyerPurchases': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuyerPurchases,
                    request_deserializer=product__pb2.GetBuyerPurchasesRequest.FromString,
                    response_serializer=product__pb2.GetBuyerPurchasesResponse.SerializeToString,
            ),
            'DisplayItems': grpc.unary_unary_rpc_method_handler(
                    servicer.DisplayItems,
                    request_deserializer=product__pb2.DisplayItemsRequest.FromString,
                    response_serializer=product__pb2.DisplayItemsResponse.SerializeToString,
            ),
            'AddToCart': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToCart,
                    request_deserializer=product__pb2.AddToCartRequest.FromString,
                    response_serializer=product__pb2.AddToCartResponse.SerializeToString,
            ),
            'RemoveFromCart': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFromCart,
                    request_deserializer=product__pb2.RemoveFromCartRequest.FromString,
                    response_serializer=product__pb2.RemoveFromCartResponse.SerializeToString,
            ),
            'ClearCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCart,
                    request_deserializer=product__pb2.ClearCartRequest.FromString,
                    response_serializer=product__pb2.ClearCartResponse.SerializeToString,
            ),
            'ClearUnsavedCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearUnsavedCart,
                    request_deserializer=product__pb2.ClearUnsavedCartRequest.FromString,
                    response_serializer=product__pb2.ClearUnsavedCartResponse.SerializeToString,
            ),
            'SaveCart': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCart,
                    request_deserializer=product__pb2.SaveCartRequest.FromString,
                    response_serializer=product__pb2.SaveCartResponse.SerializeToString,
            ),
            'ProvideItemFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.ProvideItemFeedback,
                    request_deserializer=product__pb2.ProvideItemFeedbackRequest.FromString,
                    response_serializer=product__pb2.ProvideItemFeedbackResponse.SerializeToString,
            ),
            'MakePurchase': grpc.unary_unary_rpc_method_handler(
                    servicer.MakePurchase,
                    request_deserializer=product__pb2.MakePurchaseRequest.FromString,
                    response_serializer=product__pb2.MakePurchaseResponse.SerializeToString,
            ),
            'RegisterItem': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterItem,
                    request_deserializer=product__pb2.RegisterItemRequest.FromString,
                    response_serializer=product__pb2.RegisterItemResponse.SerializeToString,
            ),
            'UpdateUnitsForSale': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUnitsForSale,
                    request_deserializer=product__pb2.UpdateUnitsForSaleRequest.FromString,
                    response_serializer=product__pb2.UpdateUnitsForSaleResponse.SerializeToString,
            ),
            'ChangeItemPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeItemPrice,
                    request_deserializer=product__pb2.ChangeItemPriceRequest.FromString,
                    response_serializer=product__pb2.ChangeItemPriceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'product.ProductService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('product.ProductService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductService(object):
    """---------------------------------------------------------------------------
    Service definition
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def SearchItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/SearchItems',
            product__pb2.SearchItemsRequest.SerializeToString,
            product__pb2.SearchItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/GetItem',
            product__pb2.GetItemRequest.SerializeToString,
            product__pb2.GetItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/GetCart',
            product__pb2.GetCartRequest.SerializeToString,
            product__pb2.GetCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBuyerPurchases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/GetBuyerPurchases',
            product__pb2.GetBuyerPurchasesRequest.SerializeToString,
            product__pb2.GetBuyerPurchasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisplayItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/DisplayItems',
            product__pb2.DisplayItemsRequest.SerializeToString,
            product__pb2.DisplayItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddToCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/AddToCart',
            product__pb2.AddToCartRequest.SerializeToString,
            product__pb2.AddToCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveFromCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/RemoveFromCart',
            product__pb2.RemoveFromCartRequest.SerializeToString,
            product__pb2.RemoveFromCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/ClearCart',
            product__pb2.ClearCartRequest.SerializeToString,
            product__pb2.ClearCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearUnsavedCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/ClearUnsavedCart',
            product__pb2.ClearUnsavedCartRequest.SerializeToString,
            product__pb2.ClearUnsavedCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/SaveCart',
            product__pb2.SaveCartRequest.SerializeToString,
            product__pb2.SaveCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProvideItemFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/ProvideItemFeedback',
            product__pb2.ProvideItemFeedbackRequest.SerializeToString,
            product__pb2.ProvideItemFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakePurchase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/MakePurchase',
            product__pb2.MakePurchaseRequest.SerializeToString,
            product__pb2.MakePurchaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/RegisterItem',
            product__pb2.RegisterItemRequest.SerializeToString,
            product__pb2.RegisterItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUnitsForSale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/UpdateUnitsForSale',
            product__pb2.UpdateUnitsForSaleRequest.SerializeToString,
            product__pb2.UpdateUnitsForSaleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeItemPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/ChangeItemPrice',
            product__pb2.ChangeItemPriceRequest.SerializeToString,
            product__pb2.ChangeItemPriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
