# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: seller.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'seller.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cseller.proto\x12\x06seller\"9\n\x13\x43reateSellerRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\":\n\x14\x43reateSellerResponse\x12\x11\n\tseller_id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2Z\n\rSellerService\x12I\n\x0c\x43reateSeller\x12\x1b.seller.CreateSellerRequest\x1a\x1c.seller.CreateSellerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'seller_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATESELLERREQUEST']._serialized_start=24
  _globals['_CREATESELLERREQUEST']._serialized_end=81
  _globals['_CREATESELLERRESPONSE']._serialized_start=83
  _globals['_CREATESELLERRESPONSE']._serialized_end=141
  _globals['_SELLERSERVICE']._serialized_start=143
  _globals['_SELLERSERVICE']._serialized_end=233
# @@protoc_insertion_point(module_scope)
